### ISSUE TITLE
"Scaling Laws for LLMs" in section 2.1 is missing in CN version

### ISSUE THREAD

**Issue by wzy816** [RUCAIBox/LLMSurvey#27]

**Comment by EliverQ** [comment]
Thank you for your interest in our work!
As we say in CN version, due to time constraints, a more accurate and comprehensive translation work is still in the planning stage. Readers are encouraged to primarily read the English version of the article. This translation version is provided for reference only and is not updated or maintained in real time. There is no guarantee that it corresponds precisely with the English version.
![image](https://user-images.githubusercontent.com/37859378/236608147-9d87ab53-fa4d-4109-9308-fd5ed9d8944f.png)

**Comment by wzy816** [comment]
> [<img alt="@EliverQ" width="40" height="40" src="https://avatars.githubusercontent.com/u/37859378?s=80&amp;u=c2a14051fa69ee7383551f84aa6031f4367cd122&amp;v=4">](/EliverQ)
> Collaborator
> ###

Thanks for the clarification by confirmation. Looking forward to any updates in the future.
